# Generated by Django 5.2.4 on 2025-08-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام فروشنده')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='اعتبار')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
            },
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ درخواستی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='recharge.seller', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'درخواست اعتبار',
                'verbose_name_plural': 'درخواست\u200cهای اعتبار',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ تراکنش')),
                ('transaction_type', models.CharField(choices=[('CREDIT_INCREASE', 'افزایش اعتبار'), ('TOPUP_SALE', 'فروش شارژ')], max_length=20, verbose_name='نوع تراکنش')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان تراکنش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='recharge.seller', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-timestamp'],
            },
        ),
    ]
